<div class="box-item1 box-poll">
<?php if(is_array($this->poll)) {?>
   <table width="100%" border="0" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="170" valign="top"><div class="poll_title">
            <a href="javascript:void(0)">Thăm dò ý kiến</a></div>
            	<div class="lable_title"><?php echo $this->poll['question']?></div>
            	<?php foreach($this->poll['choices'] as $p) :?>
	                <p>
		                <input id="choice_<?php echo $p['choice_id']?>" type="checkbox" class="check_poll" data-id="<?php echo $p['choice_id']?>">
						<label for="choice_<?php echo $p['choice_id']?>" class="label"><?php echo $p['content']?></label>
					</p>
				<?php endforeach;?>
                <div class="button_result">
                	<input id="btnVote" type="button" class="smSurevy" value="Biểu quyết">&nbsp;
                    <input id="btnViewResult" type="button" class="viewRServey" value="Xem kết quả" data-poll-id="<?php echo $this->poll['id']?>">
                </div>
            </td>
            <td width="148" align="right">
            <?php $this->action?>
            	<?php echo $this->action('simple', 'banner', 'cms', array('position' => $this->position));?>
            </td>
          </tr>
        </tbody>
   </table>      
   <?php }?> 	
</div>