<script type="text/javascript" src="<?php echo Zend_Registry::get('imgUrl')?>/js/modernizr-1.5.min.js"></script>
<script type="text/javascript" src="<?php echo Zend_Registry::get('imgUrl')?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo Zend_Registry::get('imgUrl')?>/js/jquery.easing-sooper.js"></script>
<script type="text/javascript" src="<?php echo Zend_Registry::get('imgUrl')?>/js/jquery.sooperfish.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
      $('ul.sf-menu').sooperfish();
    });
</script>