<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/thread.css" />

<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/block_adviser.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/block_best_test.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/block_member.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/block_statistics.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/thickbox.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/block_support.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/box.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/global.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/jquery.alerts.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/logo_right.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/nivo-slider.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/screen.css" />
<link rel="stylesheet" type="text/css" href="<?php echo Zend_Registry::get('imgUrl')?>/css/tooltips.css" />