<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php echo IMAGE_URL?>/css/admin/page.css" rel="stylesheet" type="text/css" />
<link href="<?php echo IMAGE_URL?>/css/admin/formapi.css" rel="stylesheet" type="text/css" />
<title>Admin Login Page</title>
</head>
<body>
<div id="wrapper">
	<div id="header">
		<?php echo $this->layout()->_section["header"] ?>
	</div>
	
	<div id="container">
		<?php echo $this->layout()->content ?>		
		<?php echo $this->layout()->_section["content"] ?>
	</div>
	
	<div id="footer">
		<?php echo $this->layout()->_section["footer"] ?>
	</div>

</div>

</body>
</html>