<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
<?php echo $this->layout()->_section['style']; ?>
<?php echo $this->layout()->_section['script'];?>
<title>Admin Management</title>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
<?php echo isset($this->layout()->_section["header"])?$this->layout()->_section["header"]:''; ?>
<div class="container-fluid">
  <div class="row-fluid">
      <?php echo $this->layout()->_section["left"]; ?>
      <div class="span9">
          <?php echo $this->layout()->content;?>
      </div>
  </div><!--/row-->

  <hr>

  <footer>
    <p>© hocgi 2013</p>
  </footer>

</div>
</body>
</html>