<h3><?php echo $this->title?></h3>
<div style="color:red;"><?php echo $this->errMessage;?></div>
<div class="upload-image">
<form action="/admin/course/save" method="post" enctype="multipart/form-data">
    <table class="table table-bordered table-striped">
        <tbody>
             <tr>
                 <td>Name</td>
                 <td>
                     <input type="text" name="name" id="name" value="<?php echo $this->course['name'];?>">
                 </td>
             </tr>
              <tr>
                 <td>Course Link</td>
                 <td>
                     <input type="text" name="course_link" id="course_link" value="<?php echo $this->course['course_link']?>">
                 </td>
             </tr>
              <tr>
                 <td>Content</td>
                 <td>
                     <textarea type="text" name="content" id="content" cols="200" rows="5" class="mceEditor">
                         <?php echo $this->course['content'];?>
                     </textarea>
                 </td>
             </tr>
              <tr>
                 <td>Schedule</td>
                 <td>
                     <textarea type="text" name="schedule" id="schedule" cols="200" rows="5" class="mceEditor">
                         <?php echo $this->course['schedule'];?>
                     </textarea>
                 </td>
             </tr>
              <tr>
                 <td>Image
                     <?php if($this->course['image']) {?>
                         <img src="<?php echo Utils_Global::get('staticUrl') . '/course/' . $this->course['hash_folder'] . '/' . $this->course['image']?>" alt="<?php echo $this->course['image']?>" width="50" height="50">
                     <?php }?>
                 </td>
                 <td>
                     <input type="file" name="file" id="file" accept="image/*" title="Chỉ chấp nhận các định dạng hình ảnh (png, jpg, jpge, gif)">
                 </td>
             </tr>
              <tr>
                 <td>Category</td>
                 <td>
                     <select name="category" id="category">
                         <?php foreach ($this->categories as $category): ?>
                             <option value="<?php echo $category['id']?>" class="optionGroup" <?php echo $this->course['category'] == $category['id']? 'selected="selected"':""?>><?php echo $category['name']?></option>
                             <?php foreach ($category['childs'] as $child):?>
                                 <option value="<?php echo $child['id']?>" class="optionChild" <?php echo $this->course['category'] == $child['id']? 'selected="selected"':""?>>--<?php echo $child['name']?></option>
                             <?php endforeach;?>
                         <?php endforeach;?>
                     </select>
                 </td>
             </tr>
              <tr>
                 <td>Center</td>
                 <td>
                     <select name="center_id" id="center_id">
                         <?php foreach ($this->centers as $center):?>
                             <option value="<?php echo $center['id']?>" class="optionGroup" <?php echo $this->course['center_id'] == $center['id']? 'selected="selected"':""?>><?php echo $center['name']?></option>
                         <?php endforeach;?>
                     </select>
                 </td>
             </tr>
              <tr>
                 <td>Tuition</td>
                 <td>
                     <input type="number" name="tuition" id="tuition" value="<?php echo $this->course['tuition']?>"/>VND
                 </td>
             </tr>
             <tr>
                 <td>Khai giảng</td>
                 <td>
                     <input type="text" name="opening_date" id="opening_date" value="<?php echo date('Y-m-d', $this->course['opening_date'])?>"/> YYYY-MM-DD
                 </td>
             </tr>
              <tr>
                 <td>Order</td>
                 <td>
                     <input type="number" name="order" id="order" value="<?php echo $this->course['order']?>"/>
                 </td>
             </tr>
             <tr>
                 <td>Active</td>
                 <td>
                     <input type="checkbox" name="active" id="active" <?php echo $this->course['active']?'checked="checked"':"";?>/>
                 </td>
             </tr>
              <tr>
                 <td>Best</td>
                 <td>
                     <input type="checkbox" name="best" id="best" <?php echo $this->course['best']?'checked="checked"':"";?>/>
                 </td>
             </tr>
              <tr>
                 <td>Hot</td>
                 <td>
                     <input type="checkbox" name="hot" id="hot" <?php echo $this->course['hot']?'checked="checked"':"";?>/>
                 </td>
             </tr>
              <tr>
                 <td>Promotion</td>
                 <td>
                     <input type="checkbox" name="promotion" id="promotion" <?php echo $this->course['promotion']?'checked="checked"':"";?>/>
                 </td>
             </tr>
             <tr>
                <td colspan="2">
                    <input type="submit" value="Save"/>
                    <a href="/admin/course/list">Cancel</a>
                </td> 
             </tr>
        </tbody>
      </table>
      <input type="hidden" value="<?php echo $this->id?>" name="id" id="id"/>
</form>
</div>
<script type="text/javascript">
tinymce.init({
	remove_script_host: false,
    relative_urls: false,
    // General options
    mode : "specific_textareas",
    editor_selector:'mceEditor',
    theme : "advanced",
    plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

    // Theme options
    theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,

    // Skin options
    skin : "o2k7",
    skin_variant : "silver",

    // Example content CSS (should be your site CSS)
    content_css : "css/example.css",

    // Drop lists for link/image/media/template dialogs
    template_external_list_url : "js/template_list.js",
    external_link_list_url : "js/link_list.js",
    external_image_list_url : "js/image_list.js",
    media_external_list_url : "js/media_list.js",
});


</script>