<?php if(!$this->isAjax) {?>
<div class="titleHN">Khóa học</div>
<?php }?>
<?php if(is_array($this->course) && $this->course) {?>
    <div id="course_detail_<?php echo $this->course['id']?>" title="Xem nhanh khóa học">
            <div class="course-title-detail clearfix">
           		<h1 class="fl"><?php echo $this->course['name']?></h1>
                <!-- a href="<?php echo $this->course['course_link']?>" class="register_course" target="_blank">ĐĂNG KÝ HỌC</a-->
          	</div>
            <div class="educator_div clearfix">
            <div class="educator_logo fr"><img src="<?php echo Utils_Global::get('staticUrl') . '/center/' . $this->course['chash_folder'] . DS .  $this->course['center_logo']?>" width="77" height="88" /></div>
                <?php echo $this->course['contact_info'];?>            	
            </div>
            <!-- text-->
            <div class="mid-content">
            	<?php echo $this->course['content']; ?>
            	<div style="font-weight: bold;">Học phí: <?php echo number_format($this->course['tuition'], 0, ',', '.'); ?> VNĐ</div>
            	<div style="font-weight: bold;">Lịch học</div>
            	<?php echo $this->course['schedule'];?>
            </div>
    </div>
<?php }?>
<script type="text/javascript">
var current_course_id = '<?php echo $this->course["id"]?>';
</script>
