<div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<?php echo $this->serverUrl()?>" target="_blank">Học gì</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              Logged in as <span style="color:white;"><?php echo $this->userName?></span>
            </p>
            <ul class="nav">
              <li><a href="<?php echo $this->serverUrl()?>/admin/auth/logout">Logout</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
