<h2>Admin Control Panel</h2>
<div id="admin_menu">
<ul class="menu">
	<li class="expanded"><a href="<?php echo BASE_URL; ?>/admin/layout/list">Layouts Management</a></li>
	<li class="leaf last"><a href="<?php echo BASE_URL; ?>/admin/block/list">Blocks Management</a></li>
	<li class="leaf last"><a href="<?php echo BASE_URL; ?>/admin/box/list">Boxes Management</a></li>
	<li class="leaf last"><a href="<?php echo BASE_URL; ?>/admin/view/list">Views Management</a></li>
</ul>
</div>