<!--
	See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
	-->
<?php if ($this->totalItemCount > $this->itemCountPerPage): ?>
	<?php if ($this->pageCount): ?> 
	<div id="paginationControl">
	 <!-- First page link -->
	<?php if (isset($this->previous)): ?>
		  <a href="<?php echo $this->url(array('page' => $this->first)) . '?' . $this->params; ?>" >&laquo; Trang đầu</a>
	<?php else: ?>
			<span></span>
	<?php endif; ?>
	
	
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?> 
	  <a href="<?php echo  $this->url(array('page' => $this->previous)) . '?' . $this->params; ?>">&lt; Trước</a> |
	<?php else: ?> 
	  <span class="disabled"></span> |
	<?php endif; ?> 
	 
	<!-- Numbered page links -->

	<?php foreach ($this->pagesInRange as $page): ?> 
	  <?php if ($page != $this->current): ?>
	    <a href="<?php echo  $this->url(array('page' => $page)) . '?' . $this->params; ?>"><?php echo $page; ?></a> |
	  <?php else: ?>
	    <?php echo $page; ?> |
	  <?php endif; ?>
	<?php endforeach; ?>
	 
	<!-- Next page link -->
	<?php if (isset($this->next)): ?> 
	  <a href="<?php echo $this->url(array('page' => $this->next)) . '?' . $this->params; ?>">Sau &gt;</a>
	<?php else: ?> 
	  <span class="disabled"></span>
	<?php endif; ?> 
	
	<!-- Last page link -->
	<?php if (isset($this->next)): ?>
		  <a href="<?php echo  $this->url(array('page' => $this->last)) . '?' . $this->params; ?>" >Trang cuối &raquo;</a>
	<?php else: ?>
		<span class="disabled PagingLastPageLnk"></span>
	<?php endif; ?>
	
	</div>
	<?php endif; ?>
<?php endif; ?>