<div class="titleHN">
   <a href="<?php echo $this->serverUrl() . $this->url(array(), 'thu_vien');?>">Thư viện</a>
</div>
<strong><?php echo $this->document['short_description']?></strong><br/></br>
<?php echo $this->document['content'];?>

<div id="download">
    <a href="javascript:void(0);"
         onclick="return Documentary.addDownloadCount('<?php echo $this->document['id']?>', '<?php echo $this->downloadUrl . '/' . $this->document['hash_download_folder'] . '/' . $this->document['file_name'];?>')" title="Tải tài liệu <?php echo $this->document['name'] . ''?>" class="download-btn">Tải về(<?php echo Utils_CommonFunction::formatSizeUnits($this->document['file_size'])?>)</a>
</div>