<div class="main-content">
<?php if($this->mangas) { foreach($this->mangas as $manga):?>
<?php
if($manga['temp_image']) {
    $href = 'javascript:void(0);';
    $imgUrl = $manga['temp_image'];
    $name = strip_tags($manga['uname']);
} else {
    $href = $this->serverUrl() . $this->url(array($manga['name_seo'], $manga['id']), 'vmg_story_detail');
    $imgUrl = $manga['chapter_image'];
    $name = strip_tags($manga['name']);
}
?>
    <div class="row spec-row truyen-che">
		<div class="truyen-che-thumbnail"> 
        	<a href="<?php echo $href; ?>" 
        	        title="<?php echo $this->seoPrefix . $name?>" target="_blank">
        	    <img src="<?php echo $imgUrl ?>" alt="<?php echo $name?>" />
    	    </a>
        </div>
        <div class="truyen-che-info">
        	<h1><a href="<?php echo $href;?>" title="<?php echo $this->seoPrefix . $name?>" target="_blank">
        	    <?php echo $name?></a></h1>
        	    <?php if($manga['manga_id']) {?>
                    <div class="stats">
                        <span class="view" style="vertical-align: top"><?php echo $manga['counter']?></span>
                        <span class="comment" style="vertical-align: top"><?php echo $manga['comment_count']?></span>
                        <span id="likeFaceBookIframe" >
        				    <iframe src="//www.facebook.com/plugins/like.php?href=<?php echo $this->serverUrl() . $this->url(array($manga['name_seo'], $manga['id']), 'vmg_story_detail');?>&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=35" 
        				        scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:168px; height:55px;" allowTransparency="true"></iframe>
        				</span>                       
                    </div>            
                <?php } else {?>
                    <div>Đang chờ kiểm duyệt!</div>
                <?php }?>
        </div>
    </div><!--end row--> 
<?php endforeach;}?>  
    <?php if($this->showPagination) {?>
        <a class="truyen-che-btn" href="<?php echo $this->serverUrl() . $this->url(array('page' => $this->page + 1), 'vmg_truyen_che_user_pagination');?>" >Xem thêm</a>
    <?php }?>
</div>