<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->render('meta-data.phtml'); ?>
<?php echo $this->layout()->_section['style']; ?>
</head>

<body>
<a name="toppage" href="#"></a>
<div id="wapper"> 
  <!-- header-->
  <div id="header">
    <?php echo $this->layout()->_section['header']?>
  </div>
  <!-- end header--> 
  <!-- header-down-->
  <div class="header-down">
    <?php require_once ('main_navigation.phtml');?>
  </div>
  <!-- end header-down-->
  <div id="wapper_container" class="container clearfix">    
   
    <!-- content-->
    <div id="content" class="clearfix">
    	<!-- center-->
      <div class="content-center fl">
      	<div class="content">
      		<?php echo $this->layout()->content;?>
            <?php echo $this->layout()->_section['other_content'];?>
         </div>
      </div>
      <!-- end center-->
      <!-- right-->
      <div class="content-right510 fr">
      	<!-- ?php echo $this->layout()->_section['right'];?-->
      	<div class="hn_advertising_dt clearfix">
        	<?php echo $this->layout()->_section['banner_top_right']?>
        </div>
      	<!-- right left-->
      	<div class="content_rightL">
        	<div class="box-item1">
            	<?php echo $this->layout()->_section['banner_right_mid']?>
            </div>
             <!-- xem nhieu-->
                <?php echo $this->layout()->_section['most_view_news']?>
           <!-- end xem nhieu-->
           <!-- video-->
           <div class="box-item1">
                <?php echo $this->layout()->_section['banner_video']?>
           </div>
           <!--end video-->
            <!-- tham do y kien-->
           <?php echo $this->layout()->_section['poll']?>
       <!-- ///-->
       	    <?php echo $this->layout()->_section['banner_mid_bottom']?>
        
        </div>
        <!-- end right left-->
        <!-- right right-->
        <div class="content_rightR">
        	<?php echo $this->layout()->_section['banner_right']?>
        </div>
        <!-- end-->
        <div class="clear"></div>
        
        <div class="hn_advertising_dt clearfix">
        	<?php echo $this->layout()->_section['banner_right_bottom']?>           
        </div>
      </div>
       <!-- end right-->
    </div>
    <!-- end content--> 
    <!-- thuong hieu-->
    <div id="PromoFooter" class="block-partner">
      <?php echo $this->layout()->_section['banner_footer'];?>
    </div>
    <!-- end thuong hieu--> 
    <!-- footer-->
    <div id="footer" class="clearfix">
      <?php echo $this->layout()->_section['footer'];?>
    </div>
    <!-- end footer--> 
  </div>
</div>
<?php require_once('register.phtml'); ?>
<?php require_once('script.phtml'); ?>
<?php echo $this->layout()->_section['script'];?>
</body>
</html>
