<script type="text/javascript">
var siteUrl = "<?php echo Utils_Global::get('siteUrl');?>";
var imgUrl = "<?php echo Utils_Global::get('imgUrl');?>";
var module = "<?php echo Utils_Global::get('module');?>";
var controller = "<?php echo Utils_Global::get('controller'); ?>";
var action = "<?php echo Utils_Global::get('action');?>";
var transaction ="<?php echo session_id();?>";
var category = "<?php echo $this->category?>";
var articleId = "<?php echo $this->articleId?>";
</script>