<h3><?php echo $this->title?></h3>
<div class="upload-image">
<div style="color:red;"><?php echo $this->errMessage;?></div>
<a href="/admin/banner/edit/position/<?php echo $this->positionId?>" style="font-weight: bold">Tạo mới</a>
<?php if(is_array($this->banners)) {?>
    <table class="table table-bordered table-striped">
        <thead>
              <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Image</th>
                <th>Link</th>
                <th>Last update</th>
                <th>Created</th>
                <th>Active</th>
                <th>WxH</th>
                <td>Note</td>
                <th>Action</th>
              </tr>
        </thead>
        <tbody>
            <?php foreach($this->banners as $banner) :?>
             <tr>
                 <td><?php echo $banner['id']?></td>
                 <td><?php echo $banner['name']?></td>
                 <td>
                     <img src="<?php echo $this->staticUrl . $banner['hash_folder'] . '/' . $banner['image']?>" width="100" height="100"/>
                 </td>
                 <td>
                     <a href="<?php echo $banner['link']?>" target="_blank">Link</a>
                 </td>
                 <td><?php echo date('d/m/Y', $banner['last_update'])?></td>
                 <td><?php echo date('d/m/Y', $banner['dateline'])?></td>
                 <td>
                     <?php if($banner['active']) {?>
                     <i class="icon-ok"></i>
                     <?php } else {?>
                     <i class="icon-lock"></i>
                     <?php }?>
                 </td>
                 <td><?php echo $banner['width']?>x<?php echo $banner['height']?></td>
                 <td><?php echo $banner['note'];?></td>
                 <td>
                     <a href="/admin/banner/edit/id/<?php echo $banner['id']?>/position/<?php echo $this->positionId;?>">
                         <i class="icon-edit"></i>
                     </a>
                     <a href="/admin/banner/delete/id/<?php echo $banner['id']?>/position/<?php echo $this->positionId;?>" onclick="return confirm('sure?');">
                         <i class="icon-remove"></i>
                     </a>
                 </td>
             </tr>
             <?php endforeach;?>
        </tbody>
      </table>
</div>
<?php } else {?>
<div>Không có tin tức nào!</div>
<?php }?>
