<div class="span3">
<div class="well sidebar-nav">
<ul class="nav nav-list">
<?php if(Business_Common_Users::checkRight('admin')) {?>
  <li class="nav-header">Admin Block Management</li>
    <li class="leaf <?php echo $this->layoutclzz?>"><a href="/admin/layout/list">Layouts Management</a></li>
	<li class="leaf last <?php echo $this->blockclzz?>"><a href="/admin/block/list">Blocks Management</a></li>
	<li class="leaf last <?php echo $this->boxclzz?>"><a href="/admin/box/list">Boxes Management</a></li>
	<li class="leaf last <?php echo $this->viewclzz?>"><a href="/admin/view/list">Views Management</a></li>
<?php }?>
   <li class="nav-header">Content management</li>
   <li class="leaf <?php echo $this->articleclzz?>"><a href="/admin/article/list?active=-1">Article Management</a></li>
	<li class="leaf last <?php echo $this->courseclzz?>"><a href="/admin/course/list">Course Management</a></li>
	<li class="leaf last <?php echo $this->centerclzz?>"><a href="/admin/center/list">Center Management</a></li>
	<li class="leaf last <?php echo $this->categoryclzz?>"><a href="/admin/category/list">Category Management</a></li>
	<li class="leaf last <?php echo $this->bannerclzz?>"><a href="/admin/banner/list">Banner & Position Management</a></li>
	<li class="leaf last <?php echo $this->imageuploadlzz?>"><a href="/admin/image-upload/upload">Image Upload Management</a></li>
<?php if(Business_Common_Users::checkRight('admin')) {?>
	<li class="nav-header">User management</li>
	<li class="leaf"><a href="/admin/users/list">User</a></li>
	<li class="leaf"><a href="/admin/roles/list">Role</a></li>
<?php }?>
</ul>
</div><!--/.well -->
</div>